spring.datasource.generate-unique-name: true
spring.datasource.url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.h2.console.enabled: true
camunda.bpm.admin-user:
  id: test
  password: test